import { Hike } from "./types";

const hikes: Hike[] = [
  {
    name: "Mount Katahdin",
    orderDate: new Date(2019, 6, 21),
    date: new Date(2019, 6, 21),
    location: "Maine, USA",
    description: ``,
    images: [
      { src: "hiking-images/19_01_katahdin/19_katahdin1.jpg", caption: "" },
      { src: "hiking-images/19_01_katahdin/19_katahdin2.jpg", caption: "" },
      { src: "hiking-images/19_01_katahdin/19_katahdin3.jpg", caption: "" },
      { src: "hiking-images/19_01_katahdin/19_katahdin4.jpg", caption: "" },
      { src: "hiking-images/19_01_katahdin/19_katahdin5.jpg", caption: "" },
      { src: "hiking-images/19_01_katahdin/19_katahdin6.jpg", caption: "" },
      { src: "hiking-images/19_01_katahdin/19_katahdin7.jpg", caption: "" },
    ],
  },
  // {
  //   name: "Secret Puzzle Lake Spot",
  //   orderDate: undefined,
  //   date: undefined,
  //   location: "",
  //   description: ``,
  //   images: [],
  // },
  // {
  //   name: "Gaspe Trip?",
  //   orderDate: undefined,
  //   date: undefined,
  //   location: "Gaspé Peninsula, Quebec, Canada",
  //   description: ``,
  //   images: [],
  // },
  {
    name: "Cinque Terre",
    orderDate: new Date(2023, 6, 8),
    date: new Date(2023, 6, 8),
    location: "Liguria, Italy",
    description: ``,
    images: [
      { src: "hiking-images/23_01_cinqueterre/23_1_cinqueterre_1.jpg", caption: "" },
      { src: "hiking-images/23_01_cinqueterre/23_1_cinqueterre_2.jpeg", caption: "" },
      { src: "hiking-images/23_01_cinqueterre/23_1_cinqueterre_3.jpeg", caption: "" },
      { src: "hiking-images/23_01_cinqueterre/23_1_cinqueterre_4.jpeg", caption: "" },
      { src: "hiking-images/23_01_cinqueterre/23_1_cinqueterre_5.jpeg", caption: "" },
      { src: "hiking-images/23_01_cinqueterre/23_1_cinqueterre_6.jpeg", caption: "" },
      { src: "hiking-images/23_01_cinqueterre/23_1_cinqueterre_7.jpeg", caption: "" },
      { src: "hiking-images/23_01_cinqueterre/23_1_cinqueterre_8.jpeg", caption: "" },
      { src: "hiking-images/23_01_cinqueterre/23_1_cinqueterre_9.PNG", caption: "" },
    ],
  },
  {
    name: "Mont Pépoiri, Mont Pétoumier, and Baus de la Frema",
    orderDate: new Date(2023, 6, 13),
    date: new Date(2023, 6, 13),
    location: "Parque National de Mercantour, France",
    description: ``,
    images: [
      { src: "hiking-images/23_02_nice/23_2_nice_7.JPG", caption: "" },
      { src: "hiking-images/23_02_nice/23_2_nice_1.jpeg", caption: "" },
      { src: "hiking-images/23_02_nice/23_2_nice_2.jpeg", caption: "" },
      { src: "hiking-images/23_02_nice/23_2_nice_3.jpeg", caption: "" },
      { src: "hiking-images/23_02_nice/23_2_nice_5.JPG", caption: "" },
      { src: "hiking-images/23_02_nice/23_2_nice_8.jpeg", caption: "" },
      { src: "hiking-images/23_02_nice/23_2_nice_9.jpeg", caption: "" },
      { src: "hiking-images/23_02_nice/23_2_nice_10.jpeg", caption: "" },
      { src: "hiking-images/23_02_nice/23_2_nice_11.jpeg", caption: "" },
    ],
  },
  {
    name: "Calanques",
    orderDate: new Date(2023, 6, 18),
    date: new Date(2023, 6, 18),
    location: "Parque National des Calanques, France",
    description: ``,
    images: [
      { src: "hiking-images/23_03_calanques/23_3_calanques_2.jpeg", caption: "" },
      { src: "hiking-images/23_03_calanques/23_3_calanques_3.jpeg", caption: "" },
      { src: "hiking-images/23_03_calanques/23_3_calanques_4.jpeg", caption: "" },
      { src: "hiking-images/23_03_calanques/23_3_calanques_5.jpeg", caption: "" },
      { src: "hiking-images/23_03_calanques/23_3_calanques_6.jpeg", caption: "" },
    ],
  },
  {
    name: "Mont Serrat",
    orderDate: new Date(2023, 6, 24),
    date: new Date(2023, 6, 24),
    location: "Spain",
    description: ``,
    images: [
      { src: "hiking-images/23_04_montserrat/23_4_montserrat_5.jpeg", caption: "" },
      { src: "hiking-images/23_04_montserrat/23_4_montserrat_1.jpeg", caption: "" },
      { src: "hiking-images/23_04_montserrat/23_4_montserrat_2.jpeg", caption: "" },
      { src: "hiking-images/23_04_montserrat/23_4_montserrat_3.jpeg", caption: "" },
      { src: "hiking-images/23_04_montserrat/23_4_montserrat_4.jpeg", caption: "" },
      { src: "hiking-images/23_04_montserrat/23_4_montserrat_6.jpeg", caption: "" },
      { src: "hiking-images/23_04_montserrat/23_4_montserrat_7.jpeg", caption: "" },
    ],
  },
  {
    name: "Signal Hill",
    orderDate: new Date(2023, 7, 2),
    date: new Date(2023, 7, 2),
    location: "St. John's, Newfoundland, Canada",
    description: ``,
    images: [
      { src: "hiking-images/23_05_signalhill/23_5_signalhill_1.JPG", caption: "" },
      { src: "hiking-images/23_05_signalhill/23_5_signalhill_2.jpeg", caption: "" },
      { src: "hiking-images/23_05_signalhill/23_5_signalhill_3.jpeg", caption: "" },
      { src: "hiking-images/23_05_signalhill/23_5_signalhill_4.jpeg", caption: "" },
    ],
  },
  {
    name: "Gross Morne",
    orderDate: new Date(2023, 7, 7),
    date: new Date(2023, 7, 7),
    location: "Gros Morne National Park, Newfoundland, Canada",
    description: ``,
    images: [
      { src: "hiking-images/23_06_grosmorne/23_6_grosmorne_4.JPG", caption: "" },
      { src: "hiking-images/23_06_grosmorne/23_6_grosmorne_1.jpeg", caption: "" },
      { src: "hiking-images/23_06_grosmorne/23_6_grosmorne_2.jpeg", caption: "" },
      { src: "hiking-images/23_06_grosmorne/23_6_grosmorne_3.jpeg", caption: "" },
      { src: "hiking-images/23_06_grosmorne/23_6_grosmorne_5.JPG", caption: "" },
      { src: "hiking-images/23_06_grosmorne/23_6_grosmorne_6.jpeg", caption: "" },
    ],
  },
  {
    name: "Maquoketa Caves",
    orderDate: new Date(2023, 7, 20),
    date: new Date(2023, 7, 20),
    location: "Iowa, USA",
    description: ``,
    images: [
      { src: "hiking-images/23_07_maquoketa_caves/23_07_maquoketa_caves_2.JPG", caption: "" },
      { src: "hiking-images/23_07_maquoketa_caves/23_07_maquoketa_caves_1.jpeg", caption: "" },
      { src: "hiking-images/23_07_maquoketa_caves/23_07_maquoketa_caves_3.jpeg", caption: "" },
      { src: "hiking-images/23_07_maquoketa_caves/23_07_maquoketa_caves_4.jpeg", caption: "" },
      { src: "hiking-images/23_07_maquoketa_caves/23_07_maquoketa_caves_5.jpeg", caption: "" },
      { src: "hiking-images/23_07_maquoketa_caves/23_07_maquoketa_caves_1.jpeg", caption: "" },
    ],
  },
  {
    name: "Badlands National Park",
    orderDate: new Date(2023, 7, 22),
    date: new Date(2023, 7, 22),
    location: "South Dakota, USA",
    description: ``,
    images: [
      { src: "hiking-images/23_08_badlands/23_08_badlands_0.JPG", caption: "" },
      { src: "hiking-images/23_08_badlands/23_08_badlands_1.JPG", caption: "" },
      { src: "hiking-images/23_08_badlands/23_08_badlands_2.jpeg", caption: "" },
      { src: "hiking-images/23_08_badlands/23_08_badlands_4.jpeg", caption: "" },
      { src: "hiking-images/23_08_badlands/23_08_badlands_5.jpeg", caption: "" },
      { src: "hiking-images/23_08_badlands/23_08_badlands_6.jpeg", caption: "" },
      { src: "hiking-images/23_08_badlands/23_08_badlands_7.jpeg", caption: "" },
      { src: "hiking-images/23_08_badlands/23_08_badlands_8.jpeg", caption: "" },
      { src: "hiking-images/23_08_badlands/23_08_badlands_9.jpeg", caption: "" },
    ],
  },
  {
    name: "Grand Teton National Park",
    orderDate: new Date(2023, 7, 25),
    date: new Date(2023, 7, 25),
    location: "Wyoming, USA",
    description: ``,
    images: [
      { src: "hiking-images/23_09_grand_teton/23_09_grand_teton_2.jpeg", caption: "" },
      { src: "hiking-images/23_09_grand_teton/23_09_grand_teton_1.jpeg", caption: "" },
      { src: "hiking-images/23_09_grand_teton/23_09_grand_teton_3.jpeg", caption: "" },
      { src: "hiking-images/23_09_grand_teton/23_09_grand_teton_4.jpeg", caption: "" },
      { src: "hiking-images/23_09_grand_teton/23_09_grand_teton_5.jpeg", caption: "" },
      { src: "hiking-images/23_09_grand_teton/23_09_grand_teton_6.jpeg", caption: "" },
      { src: "hiking-images/23_09_grand_teton/23_09_grand_teton_7.jpeg", caption: "" },
      { src: "hiking-images/23_09_grand_teton/23_09_grand_teton_8.jpeg", caption: "" },
      { src: "hiking-images/23_09_grand_teton/23_09_grand_teton_9.jpeg", caption: "" },
    ],
  },
  {
    name: "Yellowstone National Park",
    orderDate: new Date(2023, 7, 26),
    date: new Date(2023, 7, 26),
    location: "Wyoming/Montana/Idaho, USA",
    description: ``,
    images: [
      { src: "hiking-images/23_10_yellowstone/23_10_yellowstone_2.jpeg", caption: "" },
      { src: "hiking-images/23_10_yellowstone/23_10_yellowstone_3.jpeg", caption: "" },
      { src: "hiking-images/23_10_yellowstone/23_10_yellowstone_4.jpeg", caption: "" },
      { src: "hiking-images/23_10_yellowstone/23_10_yellowstone_5.jpeg", caption: "" },
      { src: "hiking-images/23_10_yellowstone/23_10_yellowstone_6.jpeg", caption: "" },
      { src: "hiking-images/23_10_yellowstone/23_10_yellowstone_7.jpeg", caption: "" },
      { src: "hiking-images/23_10_yellowstone/23_10_yellowstone_8.jpeg", caption: "" },
      { src: "hiking-images/23_10_yellowstone/23_10_yellowstone_9.jpeg", caption: "" },
      { src: "hiking-images/23_10_yellowstone/23_10_yellowstone_10.jpeg", caption: "" },
      { src: "hiking-images/23_10_yellowstone/23_10_yellowstone_1.jpeg", caption: "" },
    ],
  },
  {
    name: "Glacier National Park",
    orderDate: new Date(2023, 7, 29),
    date: new Date(2023, 7, 29),
    location: "Montana, USA",
    description: ``,
    images: [
      { src: "hiking-images/23_11_glacier/23_11_glacier_4.jpeg", caption: "" },
      { src: "hiking-images/23_11_glacier/23_11_glacier_2.jpeg", caption: "" },
      { src: "hiking-images/23_11_glacier/23_11_glacier_1.jpeg", caption: "" },
      { src: "hiking-images/23_11_glacier/23_11_glacier_3.jpeg", caption: "" },
      { src: "hiking-images/23_11_glacier/23_11_glacier_5.jpeg", caption: "" },
      { src: "hiking-images/23_11_glacier/23_11_glacier_6.jpeg", caption: "" },
      { src: "hiking-images/23_11_glacier/23_11_glacier_7.jpeg", caption: "" },
    ],
  },
  {
    name: "Mount Rainier Side Hike",
    orderDate: new Date(2023, 7, 31),
    date: new Date(2023, 7, 31),
    location: "Washington, USA",
    description: ``,
    images: [
      { src: "hiking-images/23_12_mount_rainier_1/23_12_mount_rainier_1_1.jpeg", caption: "" },
      { src: "hiking-images/23_12_mount_rainier_1/23_12_mount_rainier_1_2.jpeg", caption: "" },
      { src: "hiking-images/23_12_mount_rainier_1/23_12_mount_rainier_1_3.jpeg", caption: "" },
      { src: "hiking-images/23_12_mount_rainier_1/23_12_mount_rainier_1_4.jpeg", caption: "" },
      { src: "hiking-images/23_12_mount_rainier_1/23_12_mount_rainier_1_5.jpeg", caption: "" },
      { src: "hiking-images/23_12_mount_rainier_1/23_12_mount_rainier_1_6.jpeg", caption: "" },
      { src: "hiking-images/23_12_mount_rainier_1/23_12_mount_rainier_1_7.jpeg", caption: "" },
    ],
  },
  {
    name: "Mount Rainier",
    orderDate: new Date(2023, 8, 1),
    date: new Date(2023, 8, 1),
    location: "Washington, USA",
    description: ``,
    images: [
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_2.jpeg", caption: "" },
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_1.jpeg", caption: "" },
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_5.jpeg", caption: "" },
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_6.jpeg", caption: "" },
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_7.jpeg", caption: "" },
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_8.jpeg", caption: "" },
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_9.jpeg", caption: "" },
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_10.jpeg", caption: "" },
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_11.jpeg", caption: "" },
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_12.jpeg", caption: "" },
      { src: "hiking-images/23_13_mount_rainier_2/23_13_mount_rainier_2_13.jpeg", caption: "" },
    ],
  },
  {
    name: "Whistler",
    orderDate: new Date(2023, 8, 14),
    date: new Date(2023, 8, 14),
    location: "British Columbia, Canada",
    description: ``,
    images: [
      { src: "hiking-images/23_14_whistler/23_14_whistler_7.JPG", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_6.jpeg", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_4.jpeg", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_1.jpeg", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_10.jpeg", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_11.jpeg", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_2.jpeg", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_12.jpeg", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_3.jpeg", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_5.jpeg", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_13.jpeg", caption: "" },
      { src: "hiking-images/23_14_whistler/23_14_whistler_8.jpeg", caption: "" },
    ],
  },
  {
    name: "Mount Mansfield",
    orderDate: new Date(2024, 5, 21),
    date: new Date(2024, 5, 21),
    location: "Vermont, USA",
    description: ``,
    images: [
      { src: "hiking-images/19_01_katahdin/19_katahdin1.jpg", caption: "" },
    ],
  },
  {
    name: "Algonquin, Iroquois, and Wright Peaks",
    orderDate: new Date(2024, 6, 27),
    date: new Date(2024, 6, 27),
    location: "Adirondacks, New York, USA",
    description: ``,
    images: [
      { src: "hiking-images/19_01_katahdin/19_katahdin1.jpg", caption: "" },
    ],
  },
  {
    name: "Mount Mansfield",
    orderDate: new Date(2024, 8, 14),
    date: new Date(2024, 8, 14),
    location: "Vermont, USA",
    description: ``,
    images: [
      { src: "hiking-images/19_01_katahdin/19_katahdin1.jpg", caption: "" },
    ],
  },
  {
    name: "Kilimanjaro",
    orderDate: new Date(2025, 1, 13),
    date: new Date(2025, 1, 13),
    location: "Tanzania",
    description: ``,
    images: [
      { src: "hiking-images/19_01_katahdin/19_katahdin1.jpg", caption: "" },
    ],
  },
  {
    name: "Mount Katahdin",
    orderDate: new Date(2025, 6, 14),
    date: new Date(2025, 6, 14),
    location: "Maine, USA",
    description: ``,
    images: [
      { src: "hiking-images/19_01_katahdin/19_katahdin1.jpg", caption: "" },
    ],
  },
  {
    name: "Mount Mansfield",
    orderDate: new Date(2025, 8, 28),
    date: new Date(2025, 8, 28),
    location: "Vermont, USA",
    description: ``,
    images: [
      { src: "hiking-images/19_01_katahdin/19_katahdin1.jpg", caption: "" },
    ],
  },
];

export default hikes;
