name: bookshelf-syncer
on:
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron: "14 0,3,11,15,20,23 * * *"
    # - cron: "14 0 * * *"
  workflow_dispatch:

jobs:
  sync_goodreads_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      # - name: Run Bookshelf Syncer
      #   run: npm run sync-bookshelf
      - name: Install virtualenv
        run: pip3 install virtualenv
      - name: Create venv-bookshelf-syncer
        run: python3 -m venv ${{ github.workspace }}/venvs/venv-bookshelf-syncer
      - name: Activate venv-bookshelf-syncer
        run: source ${{ github.workspace }}/venvs/venv-bookshelf-syncer/bin/activate
      - name: Install requirements
        run: pip3 install -r ${{ github.workspace }}/src/bookshelf/syncer_v2/requirements.txt
      - name: Run 00_goodreads_scraper.py
        run: python3 ${{ github.workspace }}/src/bookshelf/syncer_v2/00_goodreads_scraper.py --working-directory ${{ github.workspace }}/src/bookshelf/syncer_v2
      - name: Run 02_all_books_flattener.py
        run: python3 ${{ github.workspace }}/src/bookshelf/syncer_v2/02_all_books_flattener.py --working-directory ${{ github.workspace }}/src/bookshelf/syncer_v2
      - name: Run 03_show_missing_thumbnails.py
        run: python3 ${{ github.workspace }}/src/bookshelf/syncer_v2/03_show_missing_thumbnails.py --working-directory ${{ github.workspace }}/src/bookshelf/syncer_v2
      - name: Deactivate venv
        run: deactivate
      - name: Commit and push changes
        run: |
          git config --global user.name "Ben Rombaut"
          git config --global user.email "rombaut.benj@gmail.com"
          
          git add .
          git commit -m "Sync Bookshelf - Automated update from GitHub Action" || exit 0  # Avoid error if no changes
          
          git push "https://${{ secrets.GITHUB_TOKEN  }}@github.com/${{ github.repository }}.git" HEAD:main
