name: bookshelf-syncer
on:
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron: "14 0,3,11,15,20,23 * * *"
    # - cron: "14 0 * * *"
  workflow_dispatch:

jobs:
  sync_f3_to_goodreads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Run Bookshelf Syncer
        run: npm run sync-bookshelf
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git commit -m "Sync Booksehfl - Automated update from GitHub Action" || exit 0  # Avoid error if no changes
          
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
