name: Sync F3 to Goodreads
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "14 0,1,2,3,11-23 * * *"
  workflow_dispatch:

jobs:
  sync_f3_to_goodreads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Create .env file
        run: |
          touch .env
          echo VUE_APP_GOODREADS_ID=${{ secrets.VUE_APP_GOODREADS_ID }} >> .env
          echo VUE_APP_GOODREADS_KEY=${{ secrets.VUE_APP_GOODREADS_KEY }} >> .env
          echo VUE_APP_API_KEY=${{ secrets.VUE_APP_API_KEY }} >> .env
          echo VUE_APP_AUTH_DOMAIN=${{ secrets.VUE_APP_AUTH_DOMAIN }} >> .env
          echo VUE_APP_PROJECT_ID=${{ secrets.VUE_APP_PROJECT_ID }} >> .env
          echo VUE_APP_STORAGE_BUCKET=${{ secrets.VUE_APP_STORAGE_BUCKET }} >> .env
          echo VUE_APP_MESSAGING_SENDER_ID=${{ secrets.VUE_APP_MESSAGING_SENDER_ID }} >> .env
          echo VUE_APP_APP_ID=${{ secrets.VUE_APP_APP_ID }} >> .env
          echo VUE_APP_MEASUREMENT_ID=${{ secrets.VUE_APP_MEASUREMENT_ID }} >> .env
          echo VUE_APP_TEST_USER_EMAIL=${{ secrets.VUE_APP_TEST_USER_EMAIL }} >> .env
          echo VUE_APP_TEST_USER_PASSWORD=${{ secrets.VUE_APP_TEST_USER_PASSWORD }} >> .env
          echo VUE_APP_FLAG_NEW_DESIGN=true >> .env
      - name: NPM Clean Install
        run: npm ci
      - name: Run Bookshelf Syncer
        run: npm run sync-bookshelf
